#!/bin/bash

# Test coverage isn't great.  This script tries to improve it by
# exercising "corner cases" that didn't come up in other tests.

die(){
    1>&2 echo "$@"
    exit 1
}
trap 'echo 1>&2 $0: Exiting on ERR trap, line: $LINENO; exit 1' ERR

set -x
me=$(basename $0)
value=hello
f=$(cd $EXPORT_ROOT && mktemp -p. $me.XXXXXX)
chmod a+rx $EXPORT_ROOT/$f
printf "%s" "$value" > $EXPORT_ROOT/$f
[ "$(cat $MTPT/$f)" = "$value" ] || die "mismatch in $me for $f for $MTPT/$f vs $EXPORT_ROOT/$f"

# Let's make sure that ls works too...
d=$(cd $EXPORT_ROOT && mktemp -d -p. $me.XXXXXX)
chmod a+rx $EXPORT_ROOT/$d
(cd $EXPORT_ROOT/$d; touch a b c; ln -s a a.symlink; echo this is a > a)

[ "$(ls $MTPT/$d | sort )" = "$(printf "a\na.symlink\nb\nc")" ] || die "output of ls doesn't look right"
[ "$(cat $MTPT/$d/a)" = "this is a" ] || die "contents of a doesn't look right"
[ "$(cat $MTPT/$d/a.symlink)" = "this is a" ] || die  "contents of a.symlink doesn't look right" 
[ "$(cat $MTPT/$d/a.symlink)" = "this is a" ] || die  "contents of a.symlink doesn't look right" 
sleep 5  # let it expire from the linkcache
[ "$(cat $MTPT/$d/a.symlink)" = "this is a" ] || die  "contents of a.symlink doesn't look right" 

# Exercise the lookup-returns ENOENT code
if errmsg=$(cat $MTPT/$d/doesnotexist 2>&1); then
    die "expected cat doesnotexist to fail"
fi
case "$errmsg" in
    *No\ such\ file\ or\ directory);;
    *) die "expected ENOENT error message.  Got ${errmsg}" ;;
esac

# Exercise the code for special files:

cat $MTPT/.fs123_config
cat $MTPT/.fs123_statistics
cat $MTPT/.fs123_server_statistics

# df will exercise statvfs
df $MTPT

# Exercise the retry codepath.  Maybe this belongs in its own test?
set -x
serverpid=$(cat $RCroot/pidfile)
kill -STOP $serverpid;
timeout 30 cat $MTPT/still-does-not-exist || true
kill -CONT  $serverpid

# the client might still be deferring connections to the
# primary.  Let's sleep for (hopefully) long enough for
# the primary to come back.  (This depends on the Fs123ConnectTimeout
# and the Fs123TransferTimeout, which are both 5).
sleep 12

# Let's try to exceed the syslog error rate.
fs123p7 ctl $MTPT LogMaxHourlyRate 10
touch $EXPORT_ROOT/$d/unreadable
chmod 0000 $EXPORT_ROOT/$d/unreadable
for i in 1 2 3 4 5 6 7 8 9 10; do
    cat $MTPT/$d/unreadable|| true
done
chmod 0755 $EXPORT_ROOT/$d/unreadable
fs123p7 ctl $MTPT LogMaxHourlyRate 3600

##############
# Let's check errno and status for a couple of bad requests.
# Should this get its own t-xxx file?
mkdir $EXPORT_ROOT/$d/dir
touch $EXPORT_ROOT/$d/regular

: ${SERVPORT:=$(cat $RCroot/portfile)}
baseurl=http://localhost:$SERVPORT/fs123/7/$PROTO_MINOR
getstatus(){
    curl -H Accept-encoding:fs123-secretbox -si "$1" | awk '/HTTP/{print $2}'
}
geterrno(){
    # ONLY FOR PROTO_MINOR=2!!
    curl -H Accept-encoding:fs123-secretbox -si "$1" | awk 'tolower($0) ~ /fs123-errno:/ { $1=""; print; }' | tr -d '[:space:]'
}

# regular is a file.  dir is a directory.  Let's ask about them "incorrectly"
if [ $PROTO_MINOR -lt 3 ]; then
    [ $(getstatus "$baseurl/d/$d/regular?128,1,0") = 200 ]
    [ $(geterrno "$baseurl/d/$d/regular?128,1,0") = 20 ] # ENOTDIR==20
    [ $(getstatus "$baseurl/f/$d/dir?128,0") = 200 ]
    [ $(geterrno "$baseurl/f/$d/dir?128,0") = 21 ] # EISDIR==21
else
    [ $(getstatus "$baseurl/d/$d/regular?128,") = 200 ]
    #[ $(geterrno "$baseurl/d/$d/regular?128,") = 20 ] # ENOTDIR==20
    [ $(getstatus "$baseurl/f/$d/dir?128,0") = 200 ]
    #[ $(geterrno "$baseurl/f/$d/dir?128,0") = 21 ] # EISDIR==21
fi

# Make some requests with bogus query-strings
[ $(getstatus "$baseurl/f/$d/regular?128,") = 400 ]
[ $(getstatus "$baseurl/f/$d/regular?128,xx") = 400 ]
[ $(getstatus "$baseurl/f/$d/regular?128,%20") = 400 ]

if [ $PROTO_MINOR -lt 3 ]; then
    [ $(getstatus "$baseurl/d/$d/dir?128,,") = 400 ]
    [ $(getstatus "$baseurl/d/$d/dir?128,xx,0") = 400 ]
    [ $(getstatus "$baseurl/d/$d/dir?128,%20,0") = 400 ]
else
    [ $(getstatus "$baseurl/d/$d/dir?x128,") = 400 ]
    [ $(getstatus "$baseurl/d/$d/dir?128x,") = 400 ]
    [ $(getstatus "$baseurl/d/$d/dir?;xx") = 400 ]
fi
############
