version: '3.8'

services:
  server:
    image: fs123rs:latest
    volumes:
      - ./:/src
      - server-target:/src/target
      - server-export:/srv/fs123
    ports:
      - 8123:8123
    init: true
    entrypoint: /src/target/debug/fs123-server --bind 0.0.0.0:8123 --max-age 3 --stale-while-revalidate 3

  client:
    image: fs123rs:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    volumes:
      - ./:/src
      - client-target:/src/target
    init: true
    entrypoint: /src/target/debug/fs123-mount -H server -p 8123 /mnt

  legacy:
    image: fs123cpp:latest
    cap_add:
      - SYS_ADMIN
    devices:
      - /dev/fuse:/dev/fuse
    environment:
      EXPORT_ROOT: /srv/fs123
      MTPT: /mnt
      PATH: /src/build:/bin:/usr/bin:/sbin:/usr/sbin
    volumes:
      - legacy:/build
      - server-export:/srv/fs123
    init: true
    entrypoint: /usr/sbin/mount.fs123p7 -f http://server:8123/ /mnt

volumes:
  server-target:
  server-export:
  client-target:
  legacy:
