#!/bin/sh
set -x
yum -y install epel-release
yum -y install gcc gcc-c++ make
yum -y install fuse fuse-devel
yum -y install libsodium-devel
yum -y install elfutils-devel
yum -y install curl-devel openssl-devel
yum -y install libevent-devel
yum -y install time attr e2fsprogs
yum -y install python36
yum -y install valgrind
yum -y install diffutils
